### ISSUE TITLE
Unable to hook into stdio?

### ISSUE THREAD

**Issue by Skarlett** [geofft/redhook#10]
I was attempting to overwrite printf, and couldn't seem to get my code to run.

```rust
// lib.rs
#[macro_use] extern crate redhook;
extern crate libc;

use libc::{c_char, c_int};

hook! {
    unsafe fn printf(format: *const c_char) -> c_int => my_printf {
        println!("injection: {}", 
        std::str::from_utf8(std::ffi::CStr::from_ptr(format).to_bytes()).expect("something went wrong"));
        0
    }
}
```
```c
// test.c
#include <stdio.h>

void main() {
    printf("Hello\n");
}
```

```sh
cargo build --release
cc test.c -o test
LD_PRELOAD=./target/release/libldpoison.so ./test
>>> "Hello"
```
--EDIT--

After some further experimentation, I found I could only use functions provided by unistd; Its unclear if this is implemented on purpose or is an accident - So I'm keeping the issue open until reviewed.

**Comment by geofft** [comment]
On my machine, gcc converts a `printf` call with no format variables into `puts`:

```
titan:/tmp geofft$ nm -D test
                 w __gmon_start__
                 U __libc_start_main
                 U puts
```

So you should be able to intercept it as long as you also hook `puts`. Can you see if that works for you?

**Comment by Skarlett** [comment]
```rust
hook! {
    unsafe fn puts(format_str: *const c_char) -> c_int => my_printf {
        println!("{:?}", string_from_c(format_str));
        0
    }
}
// Some("Hello")
```
Ah! I apologize for not knowing about that trick before. It does work now, thank you very much.
