### ISSUE TITLE
Upgrade libc to libc ^0.2

### ISSUE THREAD

**Issue by esheri3** [geofft/redhook#5]
Building a rust binary via cargo when using redhook produces the following warning (see below). Can you please consider upgrading to libc ^0.2 as libc ^0.1 appears fairly dated. Thanks!

Compiling libc v0.1.12
/home/[redacted]/.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.1.12/rust/src/liblibc/lib.rs:81:21: 81:39 warning: lint raw_pointer_derive has been removed: using derive with raw pointers is ok
/home/[redacted]/.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.1.12/rust/src/liblibc/lib.rs:81 #![allow(bad_style, raw_pointer_derive)]

**Comment by geofft** [comment]
Thanks for the poke; I hadn't touched this since libc 0.2 came out. I've published 0.1.1 to crates.io.

**Comment by esheri3** [comment]
Fantastic - thanks!
