### ISSUE TITLE
Calling original Function

### ISSUE THREAD

**Issue by n4ncy** [geofft/redhook#9]
Is there anyway to call an original function and write the output to a variable?

**Comment by geofft** [comment]
Yup - `real!(function_name)` gives you a reference to the original function, so you can do something like

```rust
hook! {
    unsafe fn orig_function(x: i32) -> i32 => my_function {
        let result = real!(orig_function)(x);
        result + 1
    }
}
```

Is that what you're looking for? I can expand on that in the README and maybe there should be an example - the readlinkspy example does this but it doesn't store the result in a variable, it just returns it immediately, and maybe there's a more interesting example.

**Comment by n4ncy** [comment]
Yup that's great thanks
